version: '3.8'

services:
    webapi:
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "5052:80"
        depends_on:
            - postgresdb1
            - postgresdb2
            - mariadb
        networks:
            - aspnetcoreapp-network
    
    postgresdb1:
        image: postgres:latest
        command:
            - -p 4001
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: password
        ports:
            - "4001:4001"
        networks:
            - aspnetcoreapp-network
    
    postgresdb2:
        image: postgres:latest
        command:
            -   -p 4000
        environment:
            POSTGRES_DB: sql_provider_postgres
            POSTGRES_USER: admin1
            POSTGRES_PASSWORD: password1
        ports:
            - "4000:4000"
        networks:
            - aspnetcoreapp-network
    
    mariadb:
        image: mariadb:latest
        environment:
            MYSQL_USER: admin
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password1
        ports:
            - "3306:3306"
        volumes:
            - postgres-data:/var/lib/postgresql/data
        networks:
            - aspnetcoreapp-network
            
volumes: 
    postgres-data: 
        
networks:
    aspnetcoreapp-network:
        driver: bridge